### ISSUE TITLE
insert new line

### ISSUE THREAD

**Issue by anton6** [kus/patch-module#1]
Is it possible to add a new line of code? Like an insert operation at line number N?

**Comment by kus** [comment]
Technically yes.

You could make it replace the line before where you want to insert with the original line plus the new line.

The reason I didn't add the feature to just add a line at X is if the code changes you wouldn't know, this way it will only insert it in if it is similar conditions to what you expect (the previous line being the same).

**Comment by anton6** [comment]
okay sounds good thanks
